### ISSUE TITLE
Test 3

### ISSUE THREAD

**Issue by TristramN** [Simprints/Android-Simprints-ID#596]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
- Device: [e.g. Samsung J6]
- Android version: [e.g. 13]
- SID version: [e.g. 2024.1.1]
- Modality: Face or Fingerprint

**Additional context**

**Comment by luhmirin-s** [comment]
The steps are not clear, please provide more information.

**Comment by TristramN** [comment]
😂
